import { codeToHtml } from "shiki";

interface ShikiCodeBlockProps {
  /** Raw source code string */
  code: string;
  /** Language for syntax highlighting */
  language: "tsx" | "ts";
  /** Optional line range to highlight [start, end] (1-indexed) */
  highlightLines?: [number, number];
  /** Optional filename displayed above the code */
  filename?: string;
}

export default async function ShikiCodeBlock({
  code,
  language,
  highlightLines,
  filename,
}: ShikiCodeBlockProps) {
  // Build line highlight decorations if provided
  const decorations: { start: { line: number; character: number }; end: { line: number; character: number }; properties: { class: string } }[] = [];
  if (highlightLines) {
    const [startLine, endLine] = highlightLines;
    for (let i = startLine - 1; i < endLine; i++) {
      decorations.push({
        start: { line: i, character: 0 },
        end: { line: i, character: Infinity },
        properties: { class: "highlight-line" },
      });
    }
  }

  const html = await codeToHtml(code, {
    lang: language,
    theme: "github-dark-default",
    decorations: decorations.length > 0 ? decorations : undefined,
  });

  // Note: dangerouslySetInnerHTML is safe here — HTML is generated by Shiki
  // from our own source files at build time, never from user input.
  return (
    <div className="shiki-code-block relative overflow-hidden rounded-lg">
      {filename && (
        <div className="flex items-center gap-2 border-b border-dark-border bg-dark-void px-4 py-2">
          <span className="font-mono text-[11px] text-text-muted">{filename}</span>
        </div>
      )}
      <div
        className="overflow-auto text-sm [&_pre]:!bg-dark-void [&_pre]:p-4 [&_code]:font-[var(--font-jetbrains-mono)] [&_.highlight-line]:bg-[#f9731620] [&_.highlight-line]:border-l-2 [&_.highlight-line]:border-l-orange-learning [&_.line]:px-1"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
